image: node:8
stages:
    - build_quick
    - build_deploy
    - build_master

build_quick:
    stage: build_quick
    only:
        - quick
    script:
        - sshpass ssh -t admin@84.201.139.43 "cd web/chat.dev.prodamus.pro/public_html && git checkout -f && git pull origin dev && npm install && npm run build"

build_deploy:
    stage: build_deploy
    only:
        - dev
    script:
        - sshpass ssh -t admin@84.201.139.43 "cd web/chat.dev.prodamus.pro/public_html && git checkout -f && git pull origin dev && npm install && npm run build"

build_master:
    stage: build_master
    only:
        - master
    script:
       - sshpass ssh -t admin@84.201.139.43 "cd web/chat.prodamus.pro/public_html && git checkout -f && git pull origin master && npm install && npm run build"
