image: node:14-alpine

stages:
  - deploy to test
  - deploy to dev
  - deploy to demo
  - deploy to prod

deploy to dev:
  stage: deploy to dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  script:
    - echo $CI_COMMIT_REF_NAME
    - sshpass ssh -t admin@84.201.139.43 "cd web/chat.dev.prodamus.pro/public_html &&
      git fetch --all &&
      git checkout -f $CI_COMMIT_REF_NAME &&
      git pull --ff-only origin $CI_COMMIT_REF_NAME &&
      npm ci && npm run build -- --mode development &&
      rm -rf build && mv dist build"

deploy to demo:
  stage: deploy to demo
  rules:
    - if: '$CI_COMMIT_BRANCH == "demo"'
      when: always
  script:
    - sshpass ssh -t admin@84.201.139.43 "cd web/chat.demo.prodamus.pro/public_html &&
      git checkout -f &&
      git pull --ff-only origin master &&
      npm ci && npm run build -- --mode demo &&
      rm -rf build && mv dist build"

deploy to prod:
  stage: deploy to prod
  only:
    - /^v[\d\.]+$/
  script:
    - sshpass ssh -t prodamus@papabot.ru -p 1002 "cd /var/www/chat.prodamus.ru/frontend &&
      git fetch --tags &&
      git checkout -f tags/$CI_COMMIT_TAG &&
      npm ci && npm run build -- --mode production &&
      rm -rf build && mv dist build"

.deploy_to_test_script:
  stage: deploy to test
  script:
    - sshpass ssh -t admin@84.201.139.43 "cd web/$SERVER_DOMAIN/public_html &&
      git fetch --all &&
      git checkout -f $CI_COMMIT_REF_NAME &&
      git pull --ff-only origin $CI_COMMIT_REF_NAME &&
      npm ci && npm run build -- --mode development &&
      rm -rf build && mv dist build"
  only:
    - /^PROD-[0-9.].*$/

deploy to dima:
  extends:
    - .deploy_to_test_script
  variables:
    SERVER_DOMAIN: dima.chat.dev.prodamus.pro
  when: manual

deploy to andrew:
  extends:
    - .deploy_to_test_script
  variables:
    SERVER_DOMAIN: andrew.chat.dev.prodamus.pro
  when: manual

deploy to nikita:
  extends:
    - .deploy_to_test_script
  variables:
    SERVER_DOMAIN: nikita.chat.dev.prodamus.pro
  when: manual
