image: node:14-alpine

stages:
  - deploy_dev
  - deploy_demo
  - deploy_prod

deploy_dev:
  stage: deploy_dev
  when: manual
  script:
    - echo $CI_COMMIT_REF_NAME
    - sshpass ssh -t admin@84.201.139.43 "cd web/chat.dev.prodamus.pro/public_html &&
      git fetch --all &&
      git checkout -f $CI_COMMIT_REF_NAME &&
      git pull --ff-only origin $CI_COMMIT_REF_NAME &&
      npm ci && npm run build -- --mode development &&
      rm -rf build && mv dist build"

deploy_demo:
  stage: deploy_demo
  when: manual
  script:
    - sshpass ssh -t admin@84.201.139.43 "cd web/chat.demo.prodamus.pro/public_html &&
      git checkout -f &&
      git pull --ff-only origin master &&
      npm ci && npm run build -- --mode demo &&
      rm -rf build && mv dist build"

deploy_prod:
  stage: deploy_prod
  only:
    - /^v[\d\.]+$/
  script:
    - sshpass ssh -t prodamus@papabot.ru -p 1002 "cd /var/www/chat.prodamus.ru/frontend &&
      git fetch --tags &&
      git checkout -f tags/$CI_COMMIT_TAG &&
      npm install &&
      npm run build &&
      rm -rf build &&
      mv dist build"
